# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NJ JAMZIT' do
pod 'Masonry'
end

target 'NJ JAMZITTests' do

end

target 'NJ JAMZITUITests' do

end

